//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RusTarihi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tsars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tsars()
        {
            this.Descriptions = new HashSet<Descriptions>();
            this.Pictures = new HashSet<Pictures>();
            this.Comments = new HashSet<Comments>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string TsarName { get; set; }
        public string Predecessor { get; set; }
        public string Successor { get; set; }
        public string Reign { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> DiedDate { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Dynasty { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descriptions> Descriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pictures> Pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
